//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiolaLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignmentRateHistory
    {
        public int RateId { get; set; }
        public int AssignmentId { get; set; }
        public decimal Wage { get; set; }
        public Nullable<System.DateTime> RateChangeDate { get; set; }
        public Nullable<byte> PaySchedule { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual JobAssignment JobAssignment { get; set; }
    }
}
