//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiolaLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountUseEntry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CountUseEntry()
        {
            this.CountUseAreas = new HashSet<CountUseArea>();
            this.CountUseBarcodes = new HashSet<CountUseBarcode>();
        }
    
        public int EntryId { get; set; }
        public int EntityId { get; set; }
        public System.DateTime EntryDateTime { get; set; }
        public int BooksCountUsed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CountUseArea> CountUseAreas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CountUseBarcode> CountUseBarcodes { get; set; }
        public virtual Entity Entity { get; set; }
    }
}
