//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiolaLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountUseArea
    {
        public int EntryAreaId { get; set; }
        public int EntryId { get; set; }
        public int AreaId { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual CountUseEntry CountUseEntry { get; set; }
    }
}
