//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiolaLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailAddress
    {
        public int EmailId { get; set; }
        public int EntityId { get; set; }
        public int EmailTypeId { get; set; }
        public string EmailAddress1 { get; set; }
        public Nullable<bool> Primary { get; set; }
        public System.Guid rowguid { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual Entity Entity { get; set; }
        public virtual EmailType EmailType { get; set; }
    }
}
