//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiolaLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeInformation
    {
        public int InformationId { get; set; }
        public int EntityId { get; set; }
        public int TypeId { get; set; }
        public string DataPoint { get; set; }
    
        public virtual EmployeeInfoType EmployeeInfoType { get; set; }
        public virtual Entity Entity { get; set; }
    }
}
