//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiolaLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityAddress
    {
        public int EntityId { get; set; }
        public int AddressId { get; set; }
        public int AddressTypeId { get; set; }
        public string Name { get; set; }
        public System.Guid rowguid { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual Entity Entity { get; set; }
        public virtual Address Address { get; set; }
        public virtual AddressType AddressType { get; set; }
    }
}
