//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiolaLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IDCharacteristic
    {
        public int CharacteristicId { get; set; }
        public int EntityIdentificationId { get; set; }
        public int CharacteristicTypeId { get; set; }
        public string Value { get; set; }
        public System.Guid rowguid { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual EntityIdentification EntityIdentification { get; set; }
        public virtual IDCharacteristicType IDCharacteristicType { get; set; }
    }
}
