//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiolaLibrary.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibraryPublicServicesEntities : DbContext
    {
        public LibraryPublicServicesEntities()
            : base("name=LibraryPublicServicesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CountDataPoint> CountDataPoints { get; set; }
        public virtual DbSet<CountUseArea> CountUseAreas { get; set; }
        public virtual DbSet<CountUseBarcode> CountUseBarcodes { get; set; }
        public virtual DbSet<CountUseEntry> CountUseEntries { get; set; }
        public virtual DbSet<InventoryBarcode> InventoryBarcodes { get; set; }
        public virtual DbSet<InventoryEntry> InventoryEntries { get; set; }
        public virtual DbSet<InventoryQueue> InventoryQueues { get; set; }
        public virtual DbSet<InventoryQueueProgress> InventoryQueueProgresses { get; set; }
        public virtual DbSet<PatronCountDataType> PatronCountDataTypes { get; set; }
        public virtual DbSet<PatronCountEntry> PatronCountEntries { get; set; }
        public virtual DbSet<SearchEntry> SearchEntries { get; set; }
        public virtual DbSet<SearchType> SearchTypes { get; set; }
        public virtual DbSet<ShelfReadingEntry> ShelfReadingEntries { get; set; }
        public virtual DbSet<ShelfReadingQueue> ShelfReadingQueues { get; set; }
        public virtual DbSet<ShelfReadingQueueProgress> ShelfReadingQueueProgresses { get; set; }
        public virtual DbSet<ShelvingEntry> ShelvingEntries { get; set; }
        public virtual DbSet<ShiftingEntry> ShiftingEntries { get; set; }
        public virtual DbSet<ShiftingQueue> ShiftingQueues { get; set; }
        public virtual DbSet<ShiftingQueueProgress> ShiftingQueueProgresses { get; set; }
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<Column> Columns { get; set; }
        public virtual DbSet<Level> Levels { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<Shelf> Shelves { get; set; }
        public virtual DbSet<ShelfFace> ShelfFaces { get; set; }
        public virtual DbSet<DatabaseLog> DatabaseLogs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<AssignmentRateHistory> AssignmentRateHistories { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeeInformation> EmployeeInformations { get; set; }
        public virtual DbSet<EmployeeInfoType> EmployeeInfoTypes { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<JobAssignment> JobAssignments { get; set; }
        public virtual DbSet<SystemAccess> SystemAccesses { get; set; }
        public virtual DbSet<SystemRequired> SystemRequireds { get; set; }
        public virtual DbSet<Entity> Entities { get; set; }
        public virtual DbSet<EntityIdentification> EntityIdentifications { get; set; }
        public virtual DbSet<EntityIDType> EntityIDTypes { get; set; }
        public virtual DbSet<IDCharacteristic> IDCharacteristics { get; set; }
        public virtual DbSet<IDCharacteristicType> IDCharacteristicTypes { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<PersonType> PersonTypes { get; set; }
        public virtual DbSet<Property> Properties { get; set; }
        public virtual DbSet<PropertyType> PropertyTypes { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<AddressType> AddressTypes { get; set; }
        public virtual DbSet<CountryRegion> CountryRegions { get; set; }
        public virtual DbSet<EmailAddress> EmailAddresses { get; set; }
        public virtual DbSet<EmailType> EmailTypes { get; set; }
        public virtual DbSet<EntityAddress> EntityAddresses { get; set; }
        public virtual DbSet<PhoneNumber> PhoneNumbers { get; set; }
        public virtual DbSet<PhoneType> PhoneTypes { get; set; }
        public virtual DbSet<StateProvince> StateProvinces { get; set; }
        public virtual DbSet<SystemsOverview> SystemsOverviews { get; set; }
    }
}
