//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiolaLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShiftingQueueProgress
    {
        public int ProgressId { get; set; }
        public int QueueId { get; set; }
        public int EntryId { get; set; }
        public System.DateTime DateTimeStart { get; set; }
        public System.DateTime DateTimeFinish { get; set; }
    
        public virtual ShiftingEntry ShiftingEntry { get; set; }
        public virtual ShiftingQueue ShiftingQueue { get; set; }
    }
}
