//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiolaLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemAccess
    {
        public int AccessId { get; set; }
        public int EntityId { get; set; }
        public int SystemId { get; set; }
        public System.DateTime DateGranted { get; set; }
        public Nullable<System.DateTime> DateRescinded { get; set; }
    
        public virtual Entity Entity { get; set; }
        public virtual SystemsOverview SystemsOverview { get; set; }
    }
}
