//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiolaLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemRequired
    {
        public int RequirementId { get; set; }
        public int JobId { get; set; }
        public int SystemId { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual SystemsOverview SystemsOverview { get; set; }
    }
}
